version: '2'
services:
    gestionproduits-app:
        image: gestionproduits
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://gestionproduits-mysql:3306/gestionproduits?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8008:8008
    gestionproduits-mysql:
        extends:
            file: mysql.yml
            service: gestionproduits-mysql
